services:
  dev-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
  test-service:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - '8080:8080'
    env_file:
      - ./.env
  production:
    build: ./
    ports:
      - '8080:8080'
    env_file:
      - ./.env